apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sampleapp-for-backstage-go
  description: |
    This is [sample app](https://github.com/monda00/sampleapp-for-backstage-go) for Backstage.
  links:
    - url: https://github.com/monda00/sampleapp-for-backstage-go
      title: GitHub Repo
      icon: github
spec:
  type: backend-app
  lifecycle: prduction
  system: backend-example-app
  owner: masa
  dependsOn:
    - resource:backend-db
  providesApis:
    - sample-api